# This file is automatically generated 
namespace eval ::wits::app { 
variable name "WiTS" 
variable long_name "Windows Inspection Tool Set" 
variable version "3.0.0" 
variable release_type "a" 
} 
