# This file is automatically generated 
namespace eval ::wits::app { 
variable name "WiTS" 
variable long_name "Windows Inspection Tool Set" 
variable version "3.0.8" 
variable release_type "b" 
} 
