APPNAME=ctcl
APPVERSIONMAJOR=0
APPVERSIONMINOR=3
APPVERSIONPATCH=0

RELEASETYPE=a
APPFILES=ctclversion.tcl mainloop.tcl ctcl.tcl
APPDESC=Tcl Console for Windows
APPAUTHOR=Ashok P. Nadkarni
APPICO=images\ctcl.ico

!include ..\..\tools\app-common.inc

